#!/usr/bin/env bash
#Requirement: Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs

#rm /etc/nginx/sites-enabled/default
#ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
#sudo service nginx restart

sudo sed -i "s/sites-enabled/sites-available/" /etc/nginx/nginx.conf
sudo service nginx restart
